:new: Sticker component
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1023
Opened 2022-01-06 13:05 UTC by julien-deramond

Closes #440 

:warning: Work In Progress base on the 2 PRs previously created.

Agreed with the designers that we can simply implement a container without placing elements with pixel perfect.

- [ ] Examples
- [ ] Documentation

2022-01-07 07:10 UTC, julien-deramond commented on scss/_variables.scss
> +$sticker-content-max-width-md:          8.1875rem !default; // Should be $sticker-size-md * .7;
- [ ] Check with the designers this behavior.

2022-01-07 14:28 UTC, louismaximepiton requested changes
Is the responsive size of font-size wanted ? -> Many spacing issues in small viewports
Maybe put a line to tell that utilities works on `.sticker` too ?

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="h2 mb-0">39,99€</span>
`.mt-1` to better fit specs.

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="display-3 mb-1">39,99€</span>
`mt-1` to better fit specs.

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="mb-1">Per month</span>
I would have done `.mb-1`, `.mb-0` and `.mb-2` on these `<span>`.

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="mb-0">With Orange Money</span>
Same as above.

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="display-1 mb-1">39,99€</span>
`.mt-2` to better fit specs

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="h3 mb-1" aria-hidden="true">Per month</span>
I would have done `.mb-1`, `.mb-1` and `.mb-2` on these `<span>`.

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="h3 mb-1">Per month</span>
I would have done `.mb-2`, `.mb-1` and `.mb-3` on these `<span>`.

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +      <span class="h3 mb-1">Bonus</span>
`.mb-2` to better fit specs

2022-01-07 14:28 UTC, louismaximepiton commented on site/content/docs/5.1/examples/stickers/index.html
> +    <div class="sticker sticker-lg">
`.pb-3` to better fit specs

2022-01-10 07:21 UTC, julien-deramond commented on scss/_variables.scss
> +$sticker-content-max-width-md:          8.1875rem !default; // Should be $sticker-size-md * .7;
FI, I changed the value from .7 to a more precise one using √2 / 2 -> .7071067812.

For the 3 sizes, the calculated width/height are:
```
scss/_variables.scss:1853 Debug: 6.1871843355rem
scss/_variables.scss:1854 Debug: 7.9549512885rem
scss/_variables.scss:1855 Debug: 12.374368671rem
```

If you draw the inner square:

<img width="150" alt="Capture d’écran 2022-01-10 à 08 08 26" src="https://user-images.githubusercontent.com/17381666/148730040-279656a9-c5a4-40f9-92d1-5cd149550750.png">

2022-01-13 15:41 UTC, louismaximepiton approved these changes
Sounds good to me.

2022-01-14 11:45 UTC, julien-deramond commented
A11y feedback from @Aniort: include the sticker's content within a `<p>` for semantics.

2022-01-20 11:22 UTC, julien-deramond commented
Last thing to do in this PR: explain that our example in not a responsive example and is just a simple example with utility classes that works for desktop.

2022-03-01 14:45 UTC, merged