Fixes for alerts
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1165
Opened 2022-03-24 09:49 UTC by louismaximepiton

Proposal to fix v4 -> v5. 

- [x] **Docs > Components > Alerts** [Sizes](https://boosted.orange.com/docs/5.1/components/alerts/#sizes): remove margin when stacked? (no design specs).
  - divide by 2 the margin, could maybe be reduced more ?
- [x] **Docs > Components > Alerts** Missing specific [Boosted message about the icons from v4](https://boosted.orange.com/docs/4.6/components/alerts/#examples).
  - Added the same as v4 one.
- [x] **Docs > Components > Alerts** Missing specific [Boosted message about the div](https://boosted.orange.com/docs/4.6/components/alerts/#additional-content) in "Additional content"
  - Added the same as v4 one.

2022-03-24 14:27 UTC, MewenLeHo requested changes

2022-03-24 14:27 UTC, MewenLeHo commented on scss/_alert.scss
> +.alert p {
As discussed, this may cause strange behaviours xith the following rule:
``
.alert-icon+* {
    margin: 0.125rem 0;
}
``

2022-05-09 08:27 UTC, MewenLeHo commented on site/content/docs/5.1/components/alerts.md
> +As of Boosted, it’s recommended to wrap your additional content in a `<div>` to ensure proper alignment — and, for headings, to always use the .alert-heading class.
Not sure about Unicode?

2022-05-09 08:28 UTC, MewenLeHo reviewed
Just one comment

2022-05-10 11:50 UTC, MewenLeHo approved these changes
👌

2022-06-02 05:23 UTC, julien-deramond commented
@louismaximepiton normal that it's been closed?

2022-06-10 06:15 UTC, julien-deramond commented on site/content/docs/5.1/components/alerts.md
> +Boosted also adds a dedicated icon for each contextual class using `.alert-icon`, matching [functional colors in palette]({{<docsref "utilities/colors#accessibility">}}):
The link shouldn't be more something like "/docs/5.x/customize/color/"?

2022-06-10 07:31 UTC, julien-deramond approved these changes

2022-06-10 07:35 UTC, merged