fix(pagination): set margin between numbers to 0
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1179
Opened 2022-04-01 15:47 UTC by hannahiss

and add new variable for margins at start and end (before and after numbers). 

Naming to see for this variable

I also had to correct line 107 to be able to commit (was sending an error), conforming to higher in the file.

closes #1120

2022-04-04 05:35 UTC, julien-deramond commented
See https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1154

2022-04-07 11:52 UTC, julien-deramond commented
Test notification.

2022-04-07 15:38 UTC, louismaximepiton requested changes
This solution seems to do the trick, but we need to introduce `// Boosted mod`

2022-04-07 15:38 UTC, louismaximepiton commented on scss/_pagination.scss
> +  @if $pagination-margin-start == (-$pagination-border-width) {
At first, I thought it could be easier to understand but it'll be harder to maintain it so let's keep it as-is to be like Bootstrap.

2022-04-07 15:38 UTC, louismaximepiton commented on scss/_pagination.scss
> +    margin-right: $pagination-margin-x-first-last;
Missing `// Boosted mod`

2022-04-07 15:38 UTC, louismaximepiton commented on scss/_pagination.scss
> +    &:not(:nth-child(2)) .page-link {
The selector could be on the same line

2022-04-07 15:38 UTC, louismaximepiton commented on scss/_variables.scss
> +$pagination-margin-x-first-last:    $spacer * .5 !default;
Missing `// Boosted mod`

2022-04-28 09:49 UTC, hannahiss commented on scss/_pagination.scss
> +  &:last-child {
Really ? Beacause it is already inside a Boosted mod comment

2022-04-28 10:14 UTC, louismaximepiton commented on scss/_pagination.scss
> +  &:last-child {
Ah yep, I didn't scroll that much, sorry about that !

2022-04-29 09:27 UTC, louismaximepiton commented on scss/_pagination.scss
> +  // Boosted mod
As discussed before : The Boosted mod isn't needed here

2022-04-29 13:02 UTC, louismaximepiton approved these changes
LGTM 🚀

2022-05-02 06:54 UTC, julien-deramond approved these changes
If easily doable please backport it to v4.

2022-05-02 06:58 UTC, merged

2022-05-02 08:11 UTC, hannahiss commented
> If easily doable please backport it to v4.
The space between numbers in pagination is already ok in v4 so no need to backport

2022-05-02 08:33 UTC, julien-deramond commented
Are you sure? I have this on `v4-dev`.

<img width="393" alt="Capture d’écran 2022-05-02 à 10 29 46" src="https://user-images.githubusercontent.com/17381666/166206858-cd260ad3-cbbc-486f-bc3c-98b21a11508e.png">

2022-05-02 08:55 UTC, hannahiss commented
You're right...  Sorry it's monday morning... I'll have a look to check how much this is complicated to fix in v4...