fix(social-btn): on dark background, need a white border on active st…
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1224
Opened 2022-04-29 07:50 UTC by hannahiss

…ate so that the size of button doesn't decrease when active (report form branch main-his-social-border-on-dark)

2022-04-29 09:09 UTC, hannahiss commented
Linked to #1121

2022-04-29 14:58 UTC, louismaximepiton commented
Just to remind what we've said in private : 
The `.active` should be back-ported to v4, since this class is actually brought by the `button-variant` mixin.

2022-05-19 13:04 UTC, hannahiss commented
> Just to remind what we've said in private : The `.active` should be back-ported to v4, since this class is actually brought by the `button-variant` mixin.

You can review. Thanks

2022-05-25 08:40 UTC, louismaximepiton requested changes
:warning: Normal social buttons are broken ⚠️

2022-05-25 08:40 UTC, louismaximepiton commented on scss/_buttons.scss
> +      border-color: $white;
This line should maybe be in another selector since it breaks the normal social buttons

2022-07-13 06:44 UTC, julien-deramond approved these changes

2022-07-13 06:46 UTC, merged