fix(doc): add small size input example
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1230
Opened 2022-04-29 15:48 UTC by hannahiss

Closes #1229

2022-05-02 12:12 UTC, louismaximepiton reviewed
IMO, we should backport the associated CSS too, but we maybe need to warn about it with an ODS alert (as the small version isn't allowed by the brand) ?

2022-06-10 08:19 UTC, hannahiss commented
I'm really not sure about the sizes of inputs, it is a proposition...

2022-06-13 08:19 UTC, louismaximepiton requested changes
I don't know if this is a good idea since we don't want to show people that they can be used, but I think we should display the small examples in the doc.

IMO, we should try to have every small input to have the same height : 30px or equivalent

2022-06-13 08:19 UTC, louismaximepiton commented on scss/forms/_form-control.scss
> +  &::file-selector-button {
Is there any way to make it 30px high ?

2022-06-13 08:19 UTC, louismaximepiton commented on scss/forms/_form-control.scss
> +.form-control-sm {
I think we should override the line-height value for sm input to make it 30px

2022-06-13 08:19 UTC, louismaximepiton commented on scss/forms/_form-select.scss
> +  padding-top: $form-select-padding-y-lg;
I think we should keep it as-is

2022-06-13 08:19 UTC, louismaximepiton commented on scss/forms/_form-select.scss
> +.form-select-sm {
We maybe need to update the line-height to have 30px height

2022-07-08 10:54 UTC, louismaximepiton approved these changes
LGTM, but we need to discuss a bit on:

* `$line-height-*` are weird to me (`$line-height-sm > $line-height-base`) but could be handled in another PR
* See on Bs why `.input-group` sizing changes padding of `.form-control` instead of having a `min-height:` like `.form-control-*` do.
* `.col-form-label-*` seems to be not aligned with the input value

2022-11-14 11:37 UTC, julien-deramond commented
There are some conflicts to resolve here @hannahiss 🙏

2022-11-15 10:37 UTC, hannahiss commented
Add small size examples to match Bootstrap examples, even if they are not part of ODS, in forms:
- Forms > Form control > Sizing
- Forms > Form control > File input
- Forms > Input group > Sizing
- Forms > Layout > Horizontal form label sizing
- Forms > Select > Sizing

Some callouts (warnings about incompatibility with ODS) should be added at all these places like in PR https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1614 (if PR https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1614 is merged before this one, should be added in this PR, if not, should be added in PR https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1614)

2022-11-15 10:38 UTC, hannahiss commented
I updated the documentation with missing mentions to small sizes (compared to Bottstrap).

2022-11-21 07:44 UTC, julien-deramond commented
Could you please update the migration guide as well?

2022-11-21 08:34 UTC, hannahiss commented
> Could you please update the migration guide as well?

I'm wondering if you should mention it, because we don't want developers to use these small examples (not compatible with ODS) ! We may discuss it on daily ?

2022-12-12 07:03 UTC, julien-deramond commented on site/content/docs/5.2/migration.md
> +- <span class="badge bg-success">New</span> Small size form controls are now available. Small inputs are defined by their `.form-control-sm`, small selects by their `.form-select-sm`. `.input-group-s
@hannahiss: I've added more info in this sentence to explain all new classes that have been added in this PR. Please check this out and suggest improvement if needed :)

2022-12-12 07:38 UTC, julien-deramond approved these changes
Pushed some minor modifications. LGTM!

2022-12-12 08:59 UTC, julien-deramond commented on site/content/docs/5.2/migration.md
> +- <span class="badge bg-success">New</span> Small size form controls are now available. Small inputs are defined by their `.form-control-sm`, small selects by their `.form-select-sm`. `.input-group-s
Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1230/commits/6d1f964d6f72971432a10c22dbc17e77a17cb131

2022-12-12 09:03 UTC, merged