Back to top : Add CSS variables
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1258
Opened 2022-05-16 14:48 UTC by louismaximepiton

2022-06-01 14:35 UTC, MewenLeHo approved these changes
Looks good 👌

2022-06-09 06:25 UTC, julien-deramond commented
@louismaximepiton there's a conflict to resolve here after the recent merge of a back-to-top fix.

2022-06-10 05:44 UTC, julien-deramond requested changes
Just few comments in order to improve the docs. Otherwise LGTM!

2022-06-10 05:44 UTC, julien-deramond commented on site/layouts/partials/footer.html
> +  <a href="#top" class="back-to-top-link btn btn-icon btn-secondary" data-bs-label="Back to top">
`data-o-label` → `data-bs-label` should be in the migration guide

2022-06-10 05:44 UTC, julien-deramond commented on site/content/docs/5.1/components/back-to-top.md
> +As part of Boosted's evolving CSS variables approach, back-to-top now use local CSS variables on `.back-to-top` for enhanced real-time customization. Values for the CSS variables are set via Sass, so
```suggestion
As part of Boosted's evolving CSS variables approach, Back to tops now use local CSS variables on `.back-to-top` for enhanced real-time customization. Values for the CSS variables are set via Sass, so Sass customization is still supported, too.
```

2022-06-10 08:49 UTC, julien-deramond approved these changes
LGTM!

2022-06-22 11:37 UTC, merged