feat(pagination): Add CSS vars for $pagination
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1268
Opened 2022-05-19 13:42 UTC by isabellechanclou

Signed-off-by: Isabelle Chanclou <isabelle.chanclou@orange.com>

Add CSS vars in Pagination component.

2022-05-25 10:11 UTC, louismaximepiton requested changes
Many review for Bootstrap side + Boosted mods

2022-05-30 15:59 UTC, louismaximepiton approved these changes
Sorry, I missed some Boosted mods with first review

2022-05-30 15:59 UTC, louismaximepiton commented on scss/_pagination.scss
> +    var(--#{$prefix}pagination-icon), // Boosted mod
Re reading this : Not in Bootstrap so forget about it

2022-05-30 15:59 UTC, louismaximepiton commented on scss/_pagination.scss
> +    var(--#{$prefix}pagination-icon), // Boosted mod
Didn't see at first but inside a Boosted mod so we don't need the comments

2022-05-31 08:04 UTC, louismaximepiton approved these changes
LGTM, few questions to answer before merging

2022-06-09 06:10 UTC, julien-deramond commented
> LGTM, few questions to answer before merging

What's the status of this PR. Approved on your side @louismaximepiton?

2022-06-09 06:21 UTC, louismaximepiton commented
Yup the PR is fine to me, but we need to propose some changes to Bs directly, since some replaced variables still exist in Bootstrap with Sass only.

2022-06-22 11:41 UTC, julien-deramond commented on scss/_pagination.scss
>    // scss-docs-start pagination-css-vars
In terms of consistency and maintenance let's keep the same order as Boostrap (you can add the Boosted specific ones wherever you want). There are no line breaks neither.

2022-06-22 11:42 UTC, julien-deramond commented on scss/_pagination.scss
> +    outline: var(--#{$prefix}pagination-focus-outline); // Boosted mod
Haven't looked at it but for this one and https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1268/files#r881440526, @isabellechanclou you could create a PR for Bootstrap to propose those modifications.

2022-06-22 11:43 UTC, julien-deramond requested changes
I let you modify the order of the CSS vars and remove the line breaks. I'll review it more in depth after. It'll be easier to review it like that for me.

2022-07-22 12:11 UTC, julien-deramond approved these changes
LGTM! Renamed `--#{$prefix}pagination-active-item-border` in `--#{$prefix}pagination-active-item-border-color` and reorder them.

Regarding new CSS vars, IMO they could be added in Bootstrap as well. However IDK if they should be all in `.pagination`, so let's try it and get some feedback.

2022-07-22 12:15 UTC, merged