feat(dropdowns): Add CSS vars for $dropdown
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1279
Opened 2022-05-24 14:28 UTC by isabellechanclou

Signed-off-by: Isabelle Chanclou <isabelle.chanclou@orange.com>

Add CSS vars for Dropdowns components.

2022-05-25 08:10 UTC, louismaximepiton requested changes
Almost there, 3 few things to tackle

2022-05-25 08:10 UTC, louismaximepiton commented on scss/_dropdown.scss
>  .dropdown-toggle {
IMO, the `.dropdown-toggle` should stay as the Bootstrap one, and IMO we should introduce a `.btn-dropdown` but in another PR ! (maybe #1164 if accepted)

2022-05-30 08:32 UTC, isabellechanclou commented on site/content/docs/5.1/components/dropdowns.md
> +- on the `.dropdown-item` class:
OK

2022-05-30 15:35 UTC, louismaximepiton requested changes
I think we had a small misunderstanding with the last commit

2022-05-30 15:35 UTC, louismaximepiton commented on scss/_dropdown.scss
> +  --#{$prefix}dropdown-item-font-weight-bold: #{$font-weight-bold}; // Boosted mod
Should be `--#{$prefix}dropdown-item-font-weight`

2022-05-30 15:35 UTC, louismaximepiton commented on site/content/docs/5.1/components/dropdowns.md
>  - on the `.dropdown-toggle` class:
Should add a line between text and shortcodes (same few lines below)

2022-05-30 15:35 UTC, louismaximepiton commented on site/content/docs/5.1/components/dropdowns.md
> +
This line should be removed to be closer to Bs

2022-05-30 15:35 UTC, louismaximepiton commented on site/content/docs/5.1/components/dropdowns.md
> +
This line should be removed to be closer to Bs

2022-07-22 13:45 UTC, MewenLeHo approved these changes
LGTM 👌

2022-07-22 14:08 UTC, merged