fix(forms): hide input control text under valid icon
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1306
Opened 2022-06-10 11:55 UTC by julien-deramond

Fixes #1305 

This PR is a proposal to fix #1305 by:
* adding the same `padding-right` rule than in Bootstrap
* avoiding to display the valid icon for Quantity Selector (not enough space)

Dear reviewer please check all possible cases in forms when inputs are valid.

### Live previews
* [Forms > Validation > Custom styles](https://deploy-preview-1306--boosted.netlify.app/docs/5.1/forms/validation/#custom-styles)
* [Forms > Validation > Supported elements](https://deploy-preview-1306--boosted.netlify.app/docs/5.1/forms/validation/#supported-elements)

2022-06-13 05:58 UTC, julien-deramond commented on scss/mixins/_forms.scss
> +      :not(.quantity-selector) > .form-control {
Before this PR, in https://boosted.netlify.app/docs/5.1/forms/validation/#supported-elements:
<img width="165" alt="Capture d’écran 2022-06-13 à 07 57 26" src="https://user-images.githubusercontent.com/17381666/173289094-18c992fc-d7cc-4b47-b321-d63e67b9a046.png">
If I don't exclude `.quantity-selector` the validation icon would be on top of the input value hiding it. I preferred to remove it entirely.

2022-07-06 12:59 UTC, louismaximepiton requested changes
The actual implementation seems to be great, but here are few questions:

Color picker could be removed too ? Or maybe do it as Bs ?
![image](https://user-images.githubusercontent.com/91960143/177552951-cc0bde4e-22ef-4685-b102-5af806422890.png)
![image](https://user-images.githubusercontent.com/91960143/177555173-839f242d-1b7f-4dbc-9f8a-90be5f010d37.png)
![image](https://user-images.githubusercontent.com/91960143/177554893-684b798e-c0ea-4c13-bcee-8f7070dcfd36.png)
![image](https://user-images.githubusercontent.com/91960143/177555095-3f96e257-31a7-468d-9113-96c009863d2a.png)


Few points that could be handled in other PR('s):

* We should remove `.is-invalid` l.249 in `validation.md`
* We should be careful for `input[type="switch"][required]:not(:checked)` invalid state (due to a filter):
![image](https://user-images.githubusercontent.com/91960143/177549404-ec89cec9-bb99-4acd-b7d0-2ccf90d3be9c.png)

2022-10-13 12:51 UTC, MewenLeHo requested changes
I think we still need the changes suggested by @louismaximepiton in his comment.
Or at least we should create a distinct issue for the problem raised by LM.

2022-10-17 12:03 UTC, julien-deramond commented
@MewenLeHo or @louismaximepiton Please check this new version including https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1306/commits/87892ff3da92ffb5231512fb4632c2870db7e11a which should fix `.form-control-color` and `.form-check-input` use cases 🤞

2022-10-17 12:23 UTC, MewenLeHo commented
> @MewenLeHo or @louismaximepiton Please check this new version including [87892ff](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/87892ff3da92ffb5231512fb4632c2870db7e11a) which should fix `.form-control-color` and `.form-check-input` use cases 🤞

LGTM 👌

2022-10-17 13:07 UTC, merged