fix(docs): bump swiper usage in custom carousel to 6.5.1
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1314
Opened 2022-06-21 06:04 UTC by julien-deramond

Closes https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1313

- [ ] Check that the HTML structure hasn't changed between the 4.5.1 and the 6.5.1
- [ ] Check that the configuration must remain the same between the 4.5.1 and the 6.5.1
- [ ] Swiper behavior without any changes has a different behavior on Firefox/Ubuntu. Swiping allows to display 2 half slides at the same time:

![Screenshot from 2022-06-21 08-03-57](https://user-images.githubusercontent.com/17381666/174727597-58b5eb15-e490-4cf8-ae38-19fe6380d514.png)

2022-06-22 07:35 UTC, louismaximepiton commented
As far as I could test myself, we can bump to `v8.2.4` without any breaking change, multiple functions were added.

2022-06-24 07:30 UTC, julien-deramond commented
There is a regression with the 6.5.1 on desktop when you swipe, it doesn't stop with a slide completely displayed but rather when you stop the movement (see screenshot). Same behavior observed with 6.5.1 and 8.2.4.

2022-06-24 09:40 UTC, louismaximepiton commented
For what I can see, if we need to go on 6.5.1 or after, there's no change between 6.5.1 and 8.2.4. However, the breaking change appear at the 6.0.0 and I can't figure out what causes the breaking change in the [release note](https://swiperjs.com/changelog#6-0-0-released-on-july-3rd-2020) do you have any idea ?

2022-06-24 09:48 UTC, julien-deramond commented
> For what I can see, if we need to go on 6.5.1 or after, there's no change between 6.5.1 and 8.2.4.

Yes agree on that. In this PR, let's go directly to 8.2.4.
So still need to check why there's a regression. Can't figure it out atm neither.

2022-06-30 08:42 UTC, julien-deramond commented
No regression with the 8.2.6 so seems good now :)

2022-06-30 09:55 UTC, louismaximepiton requested changes
I have two questions more about the changes: 
- [x] Need to update `orange-homepage` example too ?
- [x] Need to update `site\static\docs\4.6\assets\js\vendor\swiper.min.js` too ?

2022-06-30 09:55 UTC, louismaximepiton commented on package.json
> +    "swiper": "^8.2.6",
Need to change the version l.181 too ?

2022-06-30 09:55 UTC, louismaximepiton commented on package.json
> +    "swiper": "^8.2.6",
Do we need to import swiper since we import it via cdn each time we use it in the doc ?

2022-06-30 10:50 UTC, julien-deramond commented
> Need to update orange-homepage example too ?

Yes indeed

> Need to update site\static\docs\4.6\assets\js\vendor\swiper.min.js too ?

I completely deleted it and used the CDN version instead in `site/layouts/partials/scripts.html`. Should still work like that.

2022-06-30 11:06 UTC, julien-deramond commented
Need to work on this since when I change the version everywhere, the CSS is broken

2022-07-13 06:20 UTC, julien-deramond commented
Bumped the version to 8.3.0 (releases 7 days ago) and modified the CSS to fix the broken rendering of prev/next buttons.

2022-07-13 06:28 UTC, julien-deramond commented
:warning: Just saw that IE and old browser support were dropped in v5.0.0. Maybe we should stay in v4.5.1... and simply revert what's been updated in the `package*.json` (bump to v5.6.1).

2022-07-20 07:55 UTC, julien-deramond commented on config.yml
> +    css_swiper:                     "https://unpkg.com/swiper@8.3.0/swiper-bundle.min.css"
TODO:
* Switch to 8.3.1
* Revert unpkg.com and use https://cdn.jsdelivr.net/npm/swiper@8.3.1/swiper-bundle.min.css

2022-07-21 06:05 UTC, julien-deramond commented on scss/_o-carousel.scss
> -  &::after {
@isabellechanclou Without those 2 `&::after` rules we can see blue arrows:

![Screenshot from 2022-07-21 08-04-39](https://user-images.githubusercontent.com/17381666/180141023-19f52f96-5d60-4eb6-8beb-82415e5a1e85.png)

2022-07-21 07:42 UTC, julien-deramond commented on scss/_o-carousel.scss
> -  &::after {
Reintroduced CSS via 886dcbba351b0ca81787112d148e6f57ece9264a

2022-07-21 07:49 UTC, merged