Chore/merge main@????
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1345
Opened 2022-06-29 06:01 UTC by julien-deramond

- [x] https://github.com/twbs/bootstrap/commit/46bb9e78d74e0c7f4fa6f6fa611f3d9f8f28860b
- [x] https://github.com/twbs/bootstrap/commit/bb4f9d74fb399986eeeed07da10eded0908200b1
- ~~https://github.com/twbs/bootstrap/commit/e12e0806fbf7f7896316a142d732052a72b16aab~~
- ~~https://github.com/twbs/bootstrap/commit/da541014cb9caf830b77fa8993da0465b7210aac~~
- [x] https://github.com/twbs/bootstrap/commit/b5a956781f17a153626bb60ef09ef2a80dc74b8f
- ~~https://github.com/twbs/bootstrap/commit/416f4905f13c2ca3096343e0a5a4934c8c0ced3f~~
- [x] https://github.com/twbs/bootstrap/commit/73e45ee36cf4fdb6014267ecc67ba53a8b25fdae
- [ ] https://github.com/twbs/bootstrap/commit/8959bf3f0bbaca514967661a6b721a3f065f49a9
- [ ] etc.

2022-07-04 15:25 UTC, louismaximepiton requested changes
Bug on nested nav scrollspy sm breakpoint:
![image](https://user-images.githubusercontent.com/91960143/177183412-a30f2a61-39de-4abe-ae80-dd8fbe774ba5.png)

2022-07-05 05:26 UTC, julien-deramond commented
> Bug on nested nav scrollspy sm breakpoint:

This is not a regression from this branch; I can reproduce it directly in https://boosted.netlify.app/docs/5.2/components/scrollspy/. May worth creating an issue.

2022-07-05 05:34 UTC, julien-deramond commented on site/content/docs/5.2/examples/features/index.html
>          <div>
Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1345/commits/18a552f270fa1d6e4c75b5eca2323619cac6299f

2022-07-05 05:37 UTC, julien-deramond commented on site/assets/scss/_masthead.scss
> +    top: .3rem; // Boosted mod
Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1345/commits/9a825ad0cfd1303ec90de028656b251e92c0ebb5

2022-07-05 05:41 UTC, julien-deramond commented on site/layouts/partials/home/masthead.html
> +      <div class="d-flex flex-column flex-lg-row align-items-md-center justify-content-md-center gap-3 mb-4">
Definitely better with `.align-items-md-center`! Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1345/commits/56f2796c01376767ac7530f6296a8141f47fbde1

2022-07-05 10:47 UTC, louismaximepiton approved these changes
LGTM 🚀

2022-07-05 11:38 UTC, merged