Move input fields to right in segmented buttons
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1413
Opened 2022-07-26 13:44 UTC by MewenLeHo

Closes [#1365 ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1365)

2022-07-26 13:55 UTC, julien-deramond commented
Not specified in the issue but do we need to do the same (for consistency) for:
* https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#button-addons
* https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#custom-select
* https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#custom-file-input

2022-08-04 13:09 UTC, isabellechanclou commented
> Not specified in the issue but do we need to do the same (for consistency) for:

> https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#button-addons

--> No need to do the same. A callout message is planned to say its not ODS compatible (see #1199)

> https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#custom-select

--> No need to do the same. A callout message is planned to say its not ODS compatible (see #1199)

> https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#custom-file-input

--> This part will be redesign by Orange designers and will have to be modified by developers when specifications available.
Moreover, a callout message is planned (see #1199).

2022-09-13 06:31 UTC, louismaximepiton commented
Is this PR still needed regarding the fix done on main by Bootstrap ?

2022-11-21 09:30 UTC, julien-deramond commented
> Is this PR still needed regarding the fix done on main by Bootstrap ?

What's the status here?

2022-11-21 15:07 UTC, isabellechanclou commented
I've just looked at Bootstrap main branch, and the fix described here is still needed, because, not done in Bootstrap.

2022-11-22 15:28 UTC, MewenLeHo commented
> I've just looked at Bootstrap main branch, and the fix described here is still needed, because, not done in Bootstrap.

Thanks. Just done the rebase on this old pull request. We are now ready for review...

2022-11-23 08:13 UTC, louismaximepiton requested changes
> > Not specified in the issue but do we need to do the same (for consistency) for:
> 
> > https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#button-addons
> 
> --> No need to do the same. A callout message is planned to say its not ODS compatible (see #1199)
> 
> > https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#custom-select
> 
> --> No need to do the same. A callout message is planned to say its not ODS compatible (see #1199)
> 
> > https://deploy-preview-1413--boosted.netlify.app/docs/5.2/forms/input-group/#custom-file-input
> 
> --> This part will be redesign by Orange designers and will have to be modified by developers when specifications available. Moreover, a callout message is planned (see #1199).

We need to have consistency over the documentation, so if we do it once, IMO we shall do the changes everywhere.

That said, if we do the changes everywhere, I'm wondering if we can't introduce some rules to make it automated and to be transparent for users. What I have in mind: `.input-group input, .input-group input + * {margin-left: 0;}` or something similar.

2022-11-29 17:34 UTC, hannahiss requested changes
Need to add condition for textarea, but otherwise it looks good, in the button addons, segmented buttons, custom select and custom fil input, and also with validation messages in input group.

2022-11-29 17:34 UTC, hannahiss commented on scss/forms/_input-group.scss
> +  > :not(:first-child):not(.dropdown-menu):not(input):not(select):not(input + *):not(select + *)#{$validation-messages} {
missing :not(textarea):not(textarea+ *)

2022-11-30 07:47 UTC, MewenLeHo commented on scss/forms/_input-group.scss
> +  > :not(:first-child):not(.dropdown-menu):not(input):not(select):not(input + *):not(select + *)#{$validation-messages} {
But this case does not exist?

2022-12-01 11:05 UTC, hannahiss approved these changes
LGTM :-)

2022-12-02 10:21 UTC, louismaximepiton approved these changes
LGTM

2022-12-12 06:16 UTC, julien-deramond commented
Are you sure about these renderings?

![Screenshot 2022-12-12 at 07 14 14](https://user-images.githubusercontent.com/17381666/206973203-da6d10d5-7da1-437a-90a2-be41a13f5a62.png)

![Screenshot 2022-12-12 at 07 15 02](https://user-images.githubusercontent.com/17381666/206973362-9a20fd0e-c883-42fa-877c-b0d30a3e7e7c.png)

They seem off compared to the input fields

![Screenshot 2022-12-12 at 07 15 42](https://user-images.githubusercontent.com/17381666/206973584-b7f2f826-030d-4f68-b9e7-fa57016514a3.png)

2022-12-15 07:47 UTC, julien-deramond commented
@MewenLeHo Based on the discussion we had with the designers, is this PR still needed?

2022-12-15 07:54 UTC, MewenLeHo commented
> @MewenLeHo Based on the discussion we had with the designers, is this PR still needed?

Sadly, no.

2022-12-15 07:54 UTC, closed without merging