Stepped process: Adding dark variant
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1434
Opened 2022-08-01 08:22 UTC by louismaximepiton

2022-08-11 14:13 UTC, isabellechanclou commented
@julien-deramond: design specifications for states (hover and pressed) are lacking and will be asked to designers.

2022-08-24 12:38 UTC, julien-deramond commented
Haven't looked at the code but would it be possible for the "arrow separators" to be transparent rather than black (or white by default)? It would allow to use the dark variant (or the light one) on whatever background color.
![Screenshot from 2022-08-24 14-37-22](https://user-images.githubusercontent.com/17381666/186420093-1d257dc6-c5f4-4795-9e0b-af16be2e5be1.png)

2022-08-24 14:25 UTC, louismaximepiton commented
> Haven't looked at the code but would it be possible for the "arrow separators" to be transparent rather than black (or white by default)? It would allow to use the dark variant (or the light one) on whatever background color.
> 
> Here is an example of rendering with a `.bg-warning`: ![Screenshot from 2022-08-24 14-37-22](https://user-images.githubusercontent.com/17381666/186420093-1d257dc6-c5f4-4795-9e0b-af16be2e5be1.png)

I don't think so, or at least I can't see any way atm. To sum up the behavior, the arrow shape comes from a `::after` with `background-clip` and the small border comes from a `drop-shadow` implemented in the next item. If the `drop-shadow`is removed, set as transparent or inherit, we won't have the small border anymore. However, if you have any idea, feel free to make the changes on the PR directly :)

2022-08-26 12:57 UTC, julien-deramond commented
> I don't think so, or at least I can't see any way atm. To sum up the behavior, the arrow shape comes from a `::after` with `background-clip` and `background-color: inherit` and the small border comes from a `drop-shadow` implemented in the next item. If the `drop-shadow`is removed, set as transparent or inherit, we won't have the small border anymore. However, if you have any idea, feel free to make the changes on the PR directly smile

Indeed the way it is developed (and maybe there's no other way to do that) doesn't allow any transparency. So let's let it as it is for now.

2022-08-30 09:05 UTC, julien-deramond requested changes

2022-08-30 09:05 UTC, julien-deramond commented on scss/_variables.scss
> +$step-item-dark-drop-shadow:  drop-shadow($step-item-shadow-size 0 0 $black) #{"/* rtl:"} drop-shadow(-$step-item-shadow-size 0 0 $black) #{"*/"} !default;
Don't remember if the fix was here, but there is an issue with the black "arrow" and its edges:

![Screenshot from 2022-08-30 11-04-26](https://user-images.githubusercontent.com/17381666/187396698-3b972499-8847-4824-80ec-e5b84771db1f.png)

2022-08-30 09:15 UTC, louismaximepiton commented on site/content/docs/5.2/components/stepped-process.md
> +## Dark variant
However, it is different in [Close buttons](https://twbs-bootstrap.netlify.app/docs/5.2/components/close-button/#white-variant), [Dropdowns](https://twbs-bootstrap.netlify.app/docs/5.2/components/dropdowns/#dark-dropdowns) maybe we did it in the wrong way in accordions ?

2022-08-30 09:17 UTC, julien-deramond commented on site/content/docs/5.2/components/stepped-process.md
> +## Dark variant
So let's try to be consistent with what's in Bootstrap (if it's consistent there).

2022-08-30 09:44 UTC, julien-deramond commented on scss/_variables.scss
> +$step-item-dark-drop-shadow:  drop-shadow($step-item-shadow-size 0 0 $black) #{"/* rtl:"} drop-shadow(-$step-item-shadow-size 0 0 $black) #{"*/"} !default;
Seems to be a cache issue

2022-08-30 09:50 UTC, julien-deramond approved these changes
LGTM! Let's merge and come back to it if we have new information from the designers regarding some missing states.

2022-08-30 10:29 UTC, merged