Cards: quote fix
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1450
Opened 2022-08-08 15:20 UTC by louismaximepiton

Make the quotes look the same everywhere.

2022-08-23 06:17 UTC, julien-deramond requested changes
You can't change the markdown for v4 here since in v5 you don't have this `class="mb-0"`. It will impact the migration of the users. If you really want to do this modification, you'd have to change the `.blockquote-footer` rule (by handling the negative top margin as done in v5).
**Note:** In Boosted v5, we could change this value. Both elements seem to be to close to each other.

2022-08-23 09:40 UTC, louismaximepiton commented
> You can't change the markdown for v4 here since in v5 you don't have this `class="mb-0"`. It will impact the migration of the users. If you really want to do this modification, you'd have to change the `.blockquote-footer` rule (by handling the negative top margin as done in v5). **Note:** In Boosted v5, we could change this value. Both elements seem to be to close to each other.

This is done this way in [Content > Typography](https://boosted.orange.com/docs/4.6/content/typography/#naming-a-source) (Same in Bootstrap v4). However, the rendering is different between Typography and Card, so I'm wondering if this should be changed on Bs side or not at all ?

2022-09-15 07:06 UTC, julien-deramond approved these changes

2022-09-15 07:17 UTC, julien-deramond commented
Oups, bad manipulation. I'm closing it since v4 won't be maintained anymore. Let's focus on v5.

2022-09-15 07:17 UTC, closed without merging