Brand doc: Fix clear space that overlap on certain breakpoints
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1460
Opened 2022-08-12 13:40 UTC by louismaximepiton

2022-08-17 15:36 UTC, louismaximepiton reviewed
Thanks a lot for these changes, it looks way better now !

2022-08-17 15:38 UTC, isabellechanclou approved these changes

2022-08-22 10:46 UTC, julien-deramond requested changes
There's an issue with the horizontal alignment:
![Screenshot from 2022-08-22 12-42-20](https://user-images.githubusercontent.com/17381666/185903381-51284840-4d39-4fe2-8cf2-60b52b7d93f8.png)

Should stay like this:

![Screenshot from 2022-08-22 12-42-41](https://user-images.githubusercontent.com/17381666/185903431-2a13c09d-1950-4c1d-ac1d-cbe3debfabd0.png)

2022-08-23 11:44 UTC, julien-deramond approved these changes

2022-08-23 11:49 UTC, merged