Small and large buttons with icons - adjustments
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1611
Opened 2022-11-10 16:09 UTC by hannahiss

### Related issues

Closes #1122 

### Description
- set horizontal padding for small buttons to 13px instead of currently 10px - and not 15px (because in sketch horizontal padding in buttons includes 2px border). This has to be done for small buttons with or without icons
- set horizontal padding for large buttons to 18px instead of currently 20px - and not 20px (because in sketch horizontal padding in buttons includes 2px border). This has to be done for large buttons with or without icons
- Not sure about these: 
  - set icon size in small buttons to 15px instead of 16px (1rem) and change comment above (icons sizes are always a multiple of 5) => it will change buttons with icons and no labels sizes, so I'm not sure...?
  - slightly lower small buttons padding (try 1px lower). This has to be done for small buttons with or without icons => how to do this ?

### Motivation & Context
Differences between deisgn and reality in Boosted

### Types of change

- Bug fix (non-breaking which fixes an issues)

### Live previews

* https://deploy-preview-{your pr number}--boosted.netlify.app/

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [ ] My change introduces changes to the migration guide
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2022-11-14 17:24 UTC, hannahiss commented
@julien-deramond 
After a few tests and exchanges with LM and Isabelle, it seems that, for the small buttons:
- putting 15px for the icons can be problematic for centering, because the button is 30px, it doesn't fit. And in addition in the doc, users have to be told to put 0.9375rem instead of 1rem...
- if we try to lower the text by removing the 1px offset (which is line 29 of _buttons.scss), the icon also goes down. Then, if we add a padding-bottom of 1px on the icon, this icon decreases from the bottom, and we finish with the text well aligned and the icon at 15px... :-)

If this solution (remove the offset pixel + 1px padding-bottom only for small buttons) seems good to you, how to achieve it ? It would be necessary to modify the button creation mixin and I'm not sure about the good way to do this...

2022-12-12 08:27 UTC, julien-deramond commented on site/content/docs/5.2/components/buttons.md
> +  Medium button
We never use "Medium" in terms of sizing in our docs. So we should stick with a simple "Button" here IMO:

```suggestion
  Button
```

2023-01-13 08:49 UTC, hannahiss commented
After spec review, it has been decided: 
- to change icon size to 15px instead of 16px in all small buttons
- not to change the positioning of the text in small buttons (see [Franco's comment on issue](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1122#issuecomment-1380189063))

2023-01-13 15:04 UTC, louismaximepiton requested changes

2023-01-13 16:13 UTC, hannahiss commented on scss/_buttons.scss
> +  &:not(.btn-icon):not(.btn-sm) > svg {
Are you sure ? I have 8px at bottom... 
![image](https://user-images.githubusercontent.com/16681352/212366862-972b1832-ba20-4a94-96a4-8bf4e8463697.png)

2023-01-16 08:24 UTC, hannahiss commented on scss/_buttons.scss
> +    padding-bottom: $btn-icon-padding-x-sm + .0625rem;
Well, I giving it a try, but I think we're reaching the limits of what is visually acceptable...

2023-02-10 14:19 UTC, hannahiss commented
After last meeting with Franco about small buttons, he agreed visually on a version for small buttons with icons with:
- icon size 15px (.9375rem) 
- do not lower icon of 1px vertically to preserve button size (30px) (as i used to be)
- change existing icon with Solaris icon (same icon but not the same layout, the one from Solaris having some space at the border of svg square) => icon result is smaller

But **this version does not fit for icon buttons `btn-icon`: icon is not centered neither vertically nor horizontally**

Other questions:
- We need to check svg quality with Franco - for rendering - and Julien - for size: the current version has been optimized with svgo => I find the result not so great in terms of quality rendering
- We need to check if other icons in Boosted sprite are to be changed too... And if there is some impact to this/these change(s)

2024-01-04 15:40 UTC, louismaximepiton commented
FYI, Designers are working on implementing even px icons. For instance `16px` instead of `15px`. We might want them to finish first before implementing this PR.

2025-06-11 12:16 UTC, louismaximepiton commented
Closing it since we won't fix in Boosted and we already implemented it in OUDS.

2025-06-11 12:16 UTC, closed without merging