Add TikTok icon in social buttons
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1778
Opened 2023-01-12 13:56 UTC by hannahiss

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

Fixes #1766 

### Description

- add Tiktok icon
- change svg since their quality wasn't good enough, optimize them with svgo
- change hover color for Snapchat to black
- adjust sizes, change LinkedIn size to 18x18 instead of 20x20 to conform to design

### Motivation & Context

Missing TikTok icon after DSM V5 release

### Types of change

- Bug fix (non-breaking which fixes an issues)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [x] My change follows accessibility good practices; I have at least run axe

#### Design

- [x] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [x] My change is compatible with responsive display

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- (NA) I have added JavaScript unit tests to cover my changes

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- (NA) My new component is added in Storybook
- (NA) My new component is compatible with RTL
- (NA) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- (NA) Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2023-01-16 08:10 UTC, hannahiss commented
Waiting for new icons from Franco (Messenger, Discord, ...?)

2023-01-16 10:18 UTC, louismaximepiton requested changes
I think the bundle might be a bit too heavy with Solaris icons even if it looks better right now, we should see if we can have some lighter icons ?

2023-06-13 08:21 UTC, louismaximepiton approved these changes
Some wording proposals, but already seems fine to me.

2023-06-13 08:21 UTC, louismaximepiton commented on site/content/docs/5.3/migration.md
> +  - <span class="badge bg-success">New</span> TikTok social button
```suggestion
  - <span class="badge bg-success">New</span> TikTok social button.
```

2023-06-13 08:21 UTC, louismaximepiton commented on site/content/docs/5.3/components/footer.md
> +Other social icons are available. See full list in [Social buttons section]({{< docsref "/components/buttons#social-buttons" >}}).
```suggestion
See the full list of our provided socials in our [Social buttons section]({{< docsref "/components/buttons#social-buttons" >}}).
```

2023-07-04 06:27 UTC, julien-deramond commented on site/layouts/shortcodes/orange-footer.html
> +        <li><a href="#" class="btn btn-icon btn-social btn-tiktok btn-inverse"><span class="visually-hidden">Tiktok</span></a></li>
```suggestion
        <li><a href="#" class="btn btn-icon btn-social btn-tiktok btn-inverse"><span class="visually-hidden">TikTok</span></a></li>
```

2023-07-04 06:29 UTC, julien-deramond approved these changes

2023-07-04 06:32 UTC, merged