File input field component from UI Kit v5
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1783
Opened 2023-01-16 16:53 UTC by hannahiss

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

Fixes #1780 

### Description

To teh left: design asked (from Zeplin), to the right: what I cando
![image](https://user-images.githubusercontent.com/16681352/212730434-bb6fcf2b-bed8-4b96-a5be-9122e0f72867.png)

### Motivation & Context

After update of ODS with new UI kit v5, we have to make some few changes on designs in Boosted.

### Types of change

- Bug fix (non-breaking which fixes an issues)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices; I have at least run axe

#### Design

- [ ] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [ ] My change is compatible with responsive display

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- [ ] I have added JavaScript unit tests to cover my changes

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- [ ] My new component is added in Storybook
- [ ] My new component is compatible with RTL
- [ ] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [ ] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2023-01-16 17:18 UTC, hannahiss commented
## Tests with BrowserStack

### Windows/Chrome
![image](https://user-images.githubusercontent.com/16681352/212733914-0ebeb94b-16ca-445d-900f-992cad6434fd.png)

### Windows/Firefox
![image](https://user-images.githubusercontent.com/16681352/212732394-0969fb14-0a36-44f7-9d8e-4e1bb41d2720.png)

### Mac/Safari 
![image](https://user-images.githubusercontent.com/16681352/212732274-3262c05d-3ad1-4fd3-8c55-f704b32f86e9.png)

### Window/Edge
![image](https://user-images.githubusercontent.com/16681352/212732502-1b8042bb-5296-44a8-b4fa-2f4ca8e9d252.png)

### Android/Chrome
![image](https://user-images.githubusercontent.com/16681352/212733759-e6ffe12e-4511-479d-b4df-5ccca2648e88.png)

2023-01-18 11:37 UTC, louismaximepiton requested changes
Mainly missing Boosted mod and modifications due to the dark mode variables to use

FYI, I tried `:placeholder-shown` but didn't seem to work too. Just for future maintainers, can you consign the different solutions we didn't want to/couldn't do ? (js, force required, etc ..)

2023-01-18 11:37 UTC, louismaximepiton commented on scss/_variables.scss
> +$form-file-focus-border-color:      $black !default; // Boosted mod
```suggestion
$form-file-focus-border-color:      var(--#{$prefix}body-color) !default; // Boosted mod
```

or maybe just 
```suggestion
$form-file-focus-border-color:      $border-color !default; // Boosted mod
```

2023-01-18 11:37 UTC, louismaximepiton commented on scss/_variables.scss
> +$form-file-placeholder-color:       $gray-700 !default; // Boosted mod
```suggestion
$form-file-placeholder-color:       var(--#{$prefix}secondary-color) !default; // Boosted mod
```

2023-01-18 11:37 UTC, louismaximepiton commented on scss/forms/_form-control.scss
> +    color: $form-file-placeholder-color; // color of the text in the right part of input
Missing Boosted mod

2023-01-18 11:37 UTC, louismaximepiton commented on scss/forms/_form-control.scss
> +    }
Missing Boosted mod around

2023-01-18 11:37 UTC, louismaximepiton commented on scss/_variables.scss
> +$form-file-button-color:            $input-color !default;
Any specific reason to add a tabulation here ?

2023-02-13 12:26 UTC, Franco-Riccitelli commented
I can confirm we agreed the File Input font colour should be always black, except for the disabled state. I have now made this change to the Web UI Kit for Sketch and will be published in the next release of the Kit.

2023-02-28 10:17 UTC, closed without merging

2023-02-28 10:22 UTC, hannahiss commented
After design review, and technical impossibility to realize fully the design that was wanted, Franco agreed to change it slightly to match the current design => no change is needed anymore