Chore merge from 846d660
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1855
Opened 2023-02-22 13:58 UTC by julien-deramond

> **Warning**
> Must be merged after https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1854

- [x] https://github.com/twbs/bootstrap/commit/846d6606ec4eabe585dd0240e3d1b56256cfc8a6

2023-02-24 10:20 UTC, louismaximepiton requested changes
Few changes to handle before approving !

2023-02-28 08:25 UTC, julien-deramond commented on site/content/docs/5.3/examples/_index.md
> +      {{ if $entry.external }}
Tried something in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1855/commits/11f1c6ee512d8cb4edcc3a92a3a0101d8c03b761, tell me what you think of it :)

2023-02-28 08:48 UTC, julien-deramond commented on site/content/docs/5.3/migration.md
> +      <li><code>$border-radius-2xl</code></li>
Yep good catch. Done in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1855/commits/3aef7e4eaeaba4e4ef38750894f30a62a724e8bd

2023-02-28 09:17 UTC, julien-deramond commented on site/content/docs/5.3/customize/color.md
>          {{< markdown >}}`--bs-primary-text`{{< /markdown >}}
First part rather seems to be related to how Bootstrap handles `--bs-primary-*`.
For the second part, removed the section as discussed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1855/commits/0b894ebea2a25508f3aea691030d8b8aeb262354

2023-02-28 10:30 UTC, louismaximepiton approved these changes
👌

2023-02-28 10:32 UTC, merged

2023-03-01 09:39 UTC, louismaximepiton commented on site/content/docs/5.3/customize/color.md
>          {{< markdown >}}`--bs-primary-text`{{< /markdown >}}
See https://github.com/twbs/bootstrap/pull/38136