Chore merge from aa50e23 to ???
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #1927
Opened 2023-03-28 06:04 UTC by julien-deramond

- [x] https://github.com/twbs/bootstrap/commit/aa50e2361f6d51137a195907469338a14938147b

2023-03-28 08:36 UTC, MewenLeHo commented
>   * Based on the recent work on tooltips and popovers, I've only included modifications from Bootstrap as "Boosted mod"s. @MewenLeHo could you please check this commit and see if things can be modified or if I need to keep them as "Boosted mod"s?

For me we can't include their modifications if we want to keep what was merged yestersday.

2023-03-28 16:03 UTC, louismaximepiton requested changes
I think we can easily implement the Bs changes about the tooltips by changing the offset in the Js to `[0, 10]`. At least I couldn't spot any big breaking change in here.

Some changes are missing anyway for me at least.

2023-03-29 07:19 UTC, julien-deramond commented on scss/_variables.scss
> +$alert-border-radius:               var(--#{$prefix}border-radius) !default;
Oh good catch, forgot about this one (should be the only forgotten one). Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1927/commits/bbf99c066d0ee6e3c8f85e377b509190d913eeed

2023-03-29 07:21 UTC, julien-deramond commented on site/assets/js/snippets.js
Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1927/commits/a12d3302e7f70f350436c32e0700a6dfd54b4cbd

2023-03-29 07:32 UTC, julien-deramond commented
Based on the latest comment by @louismaximepiton, I tried to gather the modification and only change the `offset` to `[0, 10]`. Just checked quickly and seems to do the job. @MewenLeHo could you check it precisely since you know well the topic; the corresponding commit is https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1927/commits/686532a7591d40a62d61fb034ea44aeb0865ec04.

2023-03-29 08:10 UTC, louismaximepiton approved these changes

2023-03-29 08:11 UTC, julien-deramond commented
Put you as a reviewer @MewenLeHo just of this last part

2023-03-29 12:21 UTC, MewenLeHo approved these changes
Last part seems good.

2023-03-29 12:36 UTC, merged