Add a callout about accessibility on tooltips hiding important content
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2021
Opened 2023-05-02 15:22 UTC by hannahiss

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

Linked to PR #1823 

### Description

Add some information to developers so that they can use tooltips in the most accessible way.

### Motivation & Context

During #1823 a11y review, our expert informed us that Boosted tooltips are missing a mechanism is available to dismiss the tooltip without moving pointer hover or keyboard focus. See [WCAG site](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html). 

### Types of change

- Bug fix (non-breaking which fixes an issue)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices; I have at least run axe

#### Design

- [ ] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [ ] My change is compatible with responsive display

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- [ ] I have added JavaScript unit tests to cover my changes
- [ ] I have added SCSS unit tests to cover my changes

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- [ ] My new component is added in Storybook
- [ ] My new component is compatible with RTL
- [ ] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [ ] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2023-06-06 07:22 UTC, louismaximepiton requested changes
Some few things

2023-06-06 07:22 UTC, louismaximepiton commented on site/content/docs/5.3/components/tooltips.md
> +## Accessibility
I'd add some blank lines around this title

2023-06-06 07:22 UTC, louismaximepiton commented on site/content/docs/5.3/components/tooltips.md
TBH, I'd put this either at the very top of the page or right after the two info callouts coming from Bootstrap in `## Overview`

2023-06-06 07:22 UTC, louismaximepiton commented on site/content/docs/5.3/components/tooltips.md
> +So, developers should pay attention that the tooltip never hides an important content.
```suggestion
Please pay attention that the tooltip never hides an important content.
```

2023-06-12 06:36 UTC, louismaximepiton commented on site/content/docs/5.3/components/tooltips.md
Yeah OK, let's see what's the pov of Julien!

2023-06-12 06:36 UTC, louismaximepiton approved these changes

2023-06-12 06:49 UTC, julien-deramond commented on site/content/docs/5.3/components/tooltips.md
Maybe you can do it like in the [Dropdowns](https://deploy-preview-2021--boosted.netlify.app/docs/5.3/components/dropdowns/). Overview, then Accessibility, then Examples.

2023-06-12 07:38 UTC, julien-deramond commented on site/content/docs/5.3/components/tooltips.md
Linked to my previous comment, there's an issue in our Tooltips docs (https://twbs-bootstrap.netlify.app/docs/5.3/components/tooltips/). **Examples** shouldn't be at the same level as **Overview** (see https://twbs-bootstrap.netlify.app/docs/5.3/components/tooltips/).

So you could probably have:
1. Overview
1. Accessibility
1. Examples

2023-06-12 08:41 UTC, hannahiss commented on site/content/docs/5.3/components/tooltips.md
I'd seen it while doing the change...

2023-06-12 09:44 UTC, julien-deramond approved these changes

2023-06-12 09:52 UTC, merged