Chore merge from d8883d7
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2162
Opened 2023-07-24 13:08 UTC by julien-deramond

- [x] https://github.com/twbs/bootstrap/commit/d8883d753f45d819234b4533b58da161c4ab1e8b

2023-07-25 11:29 UTC, julien-deramond commented
@louismaximepiton I let you review this PR and in the meantime I'll check why pa11y's not happy (see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/runs/5656026746/job/15322504889?pr=2162).

2023-07-25 15:35 UTC, louismaximepiton requested changes
We should maybe add something in the migration guide about the `aria-disabled` thing ?

Should we change the `appearance` attribute for QS too ? https://github.com/twbs/bootstrap/commit/1ab75c8d14b101d7f2ab8d31f0addf549c70def7 I don't know how to test it properly. But changing its place doesn't seem to bring new errors so I'm a bit lost on this.

Few things to tackle before merging.

2023-07-25 15:35 UTC, louismaximepiton commented on site/content/docs/5.3/components/button-group.md
> +  <div class="btn-group dropstart" role="group">
**[Bootstrap Side]** The markup isn't the one shown in the doc for the dropstart.

2023-07-26 05:58 UTC, julien-deramond commented on scss/_variables.scss
Good catch! Fixed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2162/commits/12fe4835ffb151125ec3417f1f3937063523f69a

2023-07-26 05:59 UTC, julien-deramond commented on site/content/docs/5.3/components/navs-tabs.md
Can't see the context of this message, where?

2023-07-26 06:01 UTC, julien-deramond commented on site/content/docs/5.3/components/list-group.md
Fixed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2162/commits/224b13140cdb87d60a25c4901165fdefb72aece5

2023-07-26 06:07 UTC, julien-deramond commented on scss/_nav.scss
Fixed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2162/commits/be7817ff39547b615aa3ab601eb5ae3d7a919f34 (+ adapted a little our bundlewatch values)

2023-07-26 06:08 UTC, julien-deramond commented on site/data/docs-versions.yml
Damn! Fixed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2162/commits/05ebff56ea66fac9018a37f8d55d2ac3298f7081

2023-07-26 06:13 UTC, julien-deramond commented
> Should we change the appearance attribute for QS too ? https://github.com/twbs/bootstrap/commit/1ab75c8d14b101d7f2ab8d31f0addf549c70def7 I don't know how to test it properly. But changing its place doesn't seem to bring new errors so I'm a bit lost on this.

Upstream this change has been made to prevent an issue. Between the commits and the deps updates, there was a moment where the issues were actually there; and I had to do this commit https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2162/commits/53652a44d91cd002b159e5efc8c70c962a034732. There was no error with the quantity selector so I think we're good. It's reproducible anymore since the deps have changed again in the recent commits.

2023-07-26 07:17 UTC, julien-deramond commented on site/content/docs/5.3/components/navs-tabs.md
Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2162/commits/26ff4caaef9d99306d730c1dab6bb3b5e4122c4d

2023-07-26 07:32 UTC, louismaximepiton commented on site/content/docs/5.3/components/navs-tabs.md
> +        <a class="nav-link disabled" id="nav-linkD" data-bs-toggle="tab" data-bs-target="#linkD" role="tab"  aria-disabled="true">Link D</a>
```suggestion
        <a class="nav-link disabled" id="nav-linkD" data-bs-toggle="tab" data-bs-target="#linkD" role="tab" aria-disabled="true">Link D</a>
```

2023-07-26 07:32 UTC, louismaximepiton approved these changes
LGTM!

2023-07-26 07:35 UTC, merged