docs: add Icons rendering section
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2217
Opened 2023-09-05 09:47 UTC by julien-deramond

⚠️ Need to be merged after https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2075

### Description

This PR adds a section explaining how icons are built/rendered within a square and with a safe zone.

_Note: this PR can be added within https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2075 for consistency and easier review if needed._

### Motivation & Context

In projects, we are often wondering whether this safe zone is normal or not. Some designers in the projects remove them, some keep them. The purpose here is to fix this rule in our documentation.

### Types of change

- Enhancement (non-breaking change which adds functionality)

### Live previews

- https://deploy-preview-{your_pr_number}--boosted.netlify.app/docs/extend/icons/

### Checklist

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

2023-09-18 13:35 UTC, hannahiss requested changes
Maybe we could add an icon less "rounded"? Maybe tick and/or delete? The size difference would be more obvious...

2024-02-22 14:42 UTC, hannahiss reviewed
I think it's great to have theses explanations... Some comments:
- Maybe we could add an icon less "rounded"? Maybe tick and/or buy? The size difference will be more obvious...
- Icons rendering could be a level 2 title directly after the introduction of the page regarding PR #2075 
- I would add a little bit more explanations eg:
Icons are created in a square layout to maintain consistency. This square contains a safety zone that allows the icons to be used in different sizes and contexts and still be aligned as the designers wish. The size of the icons includes this safety zone.

2024-02-23 06:12 UTC, julien-deramond commented
Thanks for your comment @hannahiss! It's been taken into account in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2217/commits/d362d1571788856783755efc35280f8c037cf62b.

2024-02-23 08:54 UTC, hannahiss requested changes
there exists => there is ?
2 times ensure/ensuring => there is a designated safety zone to ensure that icons can be used in various sizes and contexts while keeping alignment as intended by the designers ?

2024-02-23 09:06 UTC, julien-deramond commented on site/content/docs/5.3/extend/icons.md
> +Icons are designed within a square layout to preserve consistency. Within this square, there exists a designated safety zone to ensure that icons can be used in various sizes and contexts while ensur
```suggestion
Icons are designed within a square layout to preserve consistency. Within this square, there exists a designated safety zone to guarantee that icons can be used in various sizes and contexts while maintaining alignment as intended by the designers. The dimensions of the icons encompass this safety zone, ensuring adaptability and consistency across diverse applications.
```

2024-02-23 09:24 UTC, hannahiss approved these changes

2024-02-23 09:57 UTC, merged