Improvement of toggle buttons borders
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2239
Opened 2023-09-13 13:44 UTC by MewenLeHo

### Related issues

Closes second part of #2163 

### Description

Coming from the work on font prototype where we now have multiple single toggle buttons not included in a `.btn-group`.
Simple solution was to make the selector a bit more specific.

### Motivation & Context

Before the change:
![screenshot-localhost_9001-2023 09 13-15_40_19](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/92363071/b7214bc8-a166-47a6-9372-2250e3b3c2fd)

After the change:
![screenshot-localhost_9001-2023 09 13-15_39_35](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/92363071/4927dd3d-a384-4703-b5a6-471dd02c6a83)

### Types of change

- Bug fix (non-breaking which fixes an issue)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- (na) My change follows accessibility good practices; I have at least run axe

#### Design

- (na) My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- (na) My change is compatible with a responsive display

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- (na) I have added JavaScript unit tests to cover my changes
- (na) I have added SCSS unit tests to cover my changes

#### Documentation

- (na) My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- (na) My new component is well displayed in [Storybook](https://deploy-preview-{your_pr_number}--boosted.netlify.app/storybook)
- [x] My new component is compatible with RTL
- [x] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [x] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- (na) Design review
- (na) A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2023-09-13 13:48 UTC, MewenLeHo commented
Not sure if an update of the migration guide is needed or not 🤔

2023-09-13 13:54 UTC, louismaximepiton commented on scss/forms/_form-check.scss
> -    &:not(:last-of-type) {
Maybe we can keep those blocks but update the selector to `.btn-group &:not(...)` ?
Seems to work on my side and would more understandable to me.

2023-09-14 07:42 UTC, louismaximepiton approved these changes
I think there's no need to have a migration note on this one.

2023-09-14 08:22 UTC, julien-deramond requested changes
There's a regression in the second example of https://deploy-preview-2239--boosted.netlify.app/docs/5.3/forms/checks-radios/#with-icon with the hover style:

![2023-09-14 10 21 02](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/a12e1866-7d23-47ab-87d9-a030dbf460d0)

2023-09-14 08:49 UTC, louismaximepiton commented
Ah yes Good catch my bad on this.

2023-09-15 08:47 UTC, louismaximepiton approved these changes
Couldn't find any other breaking change. Can't find of another way to achieve this behavior.

2023-09-20 05:44 UTC, julien-deramond approved these changes

2023-09-20 05:47 UTC, merged