Docs: Add `<details><summary>` to hide design callouts
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2548
Opened 2024-04-23 07:59 UTC by louismaximepiton

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

NA

### Description

### Motivation & Context

Following the refactoring of buttons and dropdowns.
Avoid polluting the user experience.

### Types of change

- New feature (non-breaking change which adds functionality)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [x] My change follows accessibility good practices; I have at least run axe

#### Design

- [x] My change respects the design guidelines defined in [Orange Design System](https://oran.ge/dsweb)
- [x] My change is compatible with a responsive display

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- [x] I have added JavaScript unit tests to cover my changes
- [x] I have added SCSS unit tests to cover my changes

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- [x] My new component is well displayed in [Storybook](https://deploy-preview-{your_pr_number}--boosted.netlify.app/storybook)
- [x] My new component is compatible with RTL
- [x] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [x] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2024-06-10 14:42 UTC, hannahiss reviewed
Wording should be reviewed sometimes.
The details summary should mention the incompatibility with ODS.

2024-06-10 15:03 UTC, hannahiss commented on site/content/docs/5.3/components/badge.md
>  Note that depending on how they are used, badges may be confusing for users of screen readers and similar assistive technologies. While the styling of badges provides a visual cue as to their purpose
Seen with LM: Ok for the placement of this note. 
To see if a PR should be done on Bootstrap for the "Accessibility tip"

2024-06-10 15:10 UTC, hannahiss commented on site/content/docs/5.3/components/spinners.md
> +<details>
Maybe you added an example inside an example?

2024-06-14 09:17 UTC, louismaximepiton commented on site/content/docs/5.3/components/badge.md
>  {{< design-callout-alert >}}
Since it's the first example and it is the only one visible in the page, we decided to keep it as-is.

2024-06-14 09:30 UTC, louismaximepiton commented on site/content/docs/5.3/components/carousel.md
> +<summary>See Bootstrap's variant</summary>
Can't reproduce on my side, I don't know how it could happen tbh.

2024-06-14 09:59 UTC, louismaximepiton commented on site/content/docs/5.3/components/dropdowns.md
>  {{< design-callout-alert >}}
For consistency, I'll leave it as-is.

2024-07-16 07:20 UTC, julien-deramond commented on site/content/docs/5.3/components/scrollspy.md
> +<br>
When embedded into the `<details><summary>` the example doesn't seem to work. Is there a way to make it work?

2024-07-16 07:34 UTC, julien-deramond requested changes
Great PR @louismaximepiton and @hannahiss, it's going to be helpful for the users!
Just one thing to tackle in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2548/files#r1678883911 and we're good to go

2024-07-16 07:55 UTC, julien-deramond approved these changes
I'm not a big fan of the rendering within the `<details><summary>`, but let's start with that; content and readability are more important for now.
Great job, LGTM! 🚀

2024-07-16 07:56 UTC, merged