Fix a11y audit: Remove unnecessary role="img" on aria-hidden SVGs
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2704
Opened 2024-08-22 15:46 UTC by hannahiss

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices; I have at least run axe

#### Design

- [ ] My change respects the design guidelines defined in [Orange Design System](https://oran.ge/dsweb)
- [ ] My change is compatible with a responsive display

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- [ ] I have added JavaScript unit tests to cover my changes
- [ ] I have added SCSS unit tests to cover my changes

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- [ ] My new component is well displayed in [Storybook](https://deploy-preview-{your_pr_number}--boosted.netlify.app/storybook)
- [ ] My new component is compatible with RTL
- [ ] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [ ] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2024-08-29 07:15 UTC, louismaximepiton requested changes
1 is missing also in both `orange-global-headers.html` and `orange-supra.html`.

2024-08-29 07:15 UTC, louismaximepiton commented on site/content/docs/5.3/dark-mode.md
3 are missing in here

2024-09-06 08:20 UTC, louismaximepiton approved these changes
LGTM 🚀

2024-09-17 06:23 UTC, julien-deramond reviewed
The HTML markup changed (slightly) for the headers, so it might be useful to mention it in the migration guide, isn't it?

(Note: there are some conflicts to resolve in the PR due to other PRs being merged)

2024-09-19 14:30 UTC, hannahiss commented on site/content/docs/5.3/migration.md
> +#### Orange navbar
I'm going crazy with all these PRs... This was already done in #2690 [here](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2690/files#diff-ff554e03e75f214021058bea325f4efdbe435154b706ecf220c9b29653a4ba8b), and in a better way I find... What do you think @julien-deramond

2024-09-19 14:53 UTC, hannahiss commented on site/content/docs/5.3/migration.md
> +#### Orange navbar
Anyway, I made some changes: 
- fix only `role="img"` in this PR #2704 => Change migration guide accordingly
- fix only alt attribute in PR #2690 => Change migration guide accordingly

2024-10-01 12:08 UTC, julien-deramond commented
This branch has conflicts that must be resolved after the recent merges in the _main_ branch

2024-10-03 07:00 UTC, julien-deramond commented
Apparently, thanks to your PR, we can remove one rule from `vnu-jar.mjs` → https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2704/files#diff-4ccadc344c026b116648a6acac72d1d643ec8508cc92d477371734a13c0e7e80

2024-10-03 07:28 UTC, julien-deramond approved these changes

2024-10-03 07:28 UTC, merged