Button component
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2804
Opened 2024-11-26 18:01 UTC by hannahiss

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_
⚠️ 🚧  !! DRAFT !! 🚧 ⚠️

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Live previews

- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/>

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices; I have at least run axe

#### Design

- [ ] My change respects the design guidelines defined in [Orange Design System](https://oran.ge/dsweb)
- [ ] My change is compatible with a responsive display

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- [ ] I have added JavaScript unit tests to cover my changes
- [ ] I have added SCSS unit tests to cover my changes

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- [ ] My new component is well displayed in [Storybook](https://deploy-preview-{your_pr_number}--boosted.netlify.app/storybook)
- [ ] My new component is compatible with RTL
- [ ] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [ ] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

2025-01-09 17:19 UTC, hannahiss commented on scss/_variables.scss
> +$input-padding-y:                       .5rem !default;
Yes, that was the idea...

2025-01-09 17:19 UTC, hannahiss commented on site/content/docs/0.0/examples/loading-buttons/index.html
> +---
I add a proposition to display js code

2025-01-09 17:22 UTC, hannahiss commented on site/content/docs/0.0/examples/loading-buttons/loading-buttons.js
> +      clearTimeout(updateStatusMessageCall1)
oups

2025-01-21 17:46 UTC, louismaximepiton requested changes
Haven't checked the component metricsi n details yet, but they look fine for now.
Still need to check the relation between tokens/variables and the component.
We can uncomment things in:
- Introduction -> Link to uncomment

2025-01-24 16:21 UTC, hannahiss commented on scss/_buttons.scss
> +  @keyframes rotate-determinate {
yes can be done later..

2025-01-24 16:35 UTC, hannahiss commented on scss/_buttons.scss
> +  &:not(.btn-icon):has(> .icon) {
need more explanations :-)

2025-01-24 16:37 UTC, hannahiss commented on scss/_buttons.scss
> +  --#{$prefix}btn-disabled-opacity: #{$btn-disabled-opacity}; // TODO to check
nothing, it's ok :-)

2025-01-24 16:40 UTC, hannahiss commented on scss/_buttons.scss
> +  &.disabled,
It was about links, where disabled does not exist... About the class, if we don't use ti, it should be added to the migration guide, I hadn't have it mind

2025-01-24 16:42 UTC, hannahiss commented on scss/_buttons.scss
> +  }
LM, you changed the values in here and I find it is not working well on my side... To be seen together

2025-01-27 08:33 UTC, louismaximepiton commented
We should probably map `.btn-link` to `.btn-minimal`

2025-01-28 09:06 UTC, nilloq commented on site/content/docs/0.0/helpers/stretched-link.md
Ok done

2025-01-28 09:06 UTC, nilloq commented on site/content/docs/0.0/helpers/stretched-link.md
> +    <a href="#" class="btn btn-default stretched-link">Go somewhere</a>
Ok taken into account

2025-01-28 09:19 UTC, nilloq commented on site/content/docs/0.0/migration-from-boosted.md
> +  - `.btn-info`and `.btn-light` will look as `.btn-minimal`
Ok fixed

2025-01-28 15:07 UTC, nilloq commented on site/assets/scss/_content.scss
> +// OUDS mod: some values have been changed in the following `custom-color-mode` and `.btn-dropdown` is used instead of `.btn-default`
Revert done

2025-01-28 15:22 UTC, nilloq commented on site/content/docs/0.0/extend/approach.md
> +As such, components should be built with a base class that houses common, not-to-be overridden property-value pairs. For example, `.btn` and `.btn-default`. We use `.btn` for all the common styles li
Ok fixed

2025-01-28 15:29 UTC, nilloq commented on site/content/docs/0.0/migration-from-boosted.md
> +You will have to make some extra Javascript to change the styles and update the status message like explained in the documentation. You can find a complete example in our [loading buttons live exampl
See https://boosted.orange.com/docs/5.3/migration/#examples

2025-02-05 11:03 UTC, louismaximepiton commented on site/assets/scss/_content.scss
> +// OUDS mod: some values have been changed in the following `custom-color-mode` and `.btn-dropdown` is used instead of `.btn-default`
Need to check about the doc

2025-02-06 09:34 UTC, louismaximepiton commented on scss/_buttons.scss
> +  }
Changed it, it should be better now.

2025-02-06 10:14 UTC, louismaximepiton commented on scss/_buttons.scss
> +  &.loading-determinate {
Wait until we have the spinner component.

2025-02-06 10:43 UTC, louismaximepiton commented on site/assets/scss/_component-examples.scss
> -  > .btn,
Tried something.

2025-02-17 17:32 UTC, hannahiss reviewed
Loading buttons still to fix and enhance...

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Default</span>
```suggestion
    <span class="visually-hidden d-none">Download file 5</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Strong</span>
```suggestion
    <span class="visually-hidden d-none">Download file 6</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Minimal</span>
```suggestion
    <span class="visually-hidden d-none">Download file 7</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Negative</span>
```suggestion
    <span class="visually-hidden d-none">Download file 8</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Default</span>
```suggestion
    <span class="visually-hidden d-none">Download file 13</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Strong</span>
```suggestion
    <span class="visually-hidden d-none">Download file 14</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Minimal</span>
```suggestion
    <span class="visually-hidden d-none">Download file 15</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +    <span class="visually-hidden d-none">Negative</span>
```suggestion
    <span class="visually-hidden d-none">Download file 16</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +        <span class="visually-hidden d-none">Default</span>
```suggestion
        <span class="visually-hidden d-none">Download file 20</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +        <span class="visually-hidden d-none">Strong</span>
```suggestion
        <span class="visually-hidden d-none">Download file 21</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +        <span class="visually-hidden d-none">Minimal</span>
```suggestion
        <span class="visually-hidden d-none">Download file 22</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +{{< example class="p-none" >}}
Maybe, for a better presentation, I would hav split the example in two: buttons and the icon buttons, with an introduction sentence like: "loading state can also be combined with icon buttons". Maybe it is not necessary to have all sorts of icon button, since the logic is always the same... Plus the is also buttons with icon AND text...

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +      <span class="visually-hidden d-none">Default</span>
```suggestion
      <span class="visually-hidden d-none">Download file 26</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +      <span class="visually-hidden d-none">Strong</span>
```suggestion
      <span class="visually-hidden d-none">Download file 27</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/components/buttons.md
> +      <span class="visually-hidden d-none">Minimal</span>
```suggestion
      <span class="visually-hidden d-none">Download file 28</span>
```

2025-02-17 17:32 UTC, hannahiss commented on site/content/docs/0.1/examples/loading-buttons/index.html
> +        Download file 1
When I test the loading buttons, the animations are broken... 
I would have also add an example of a loading icon button since it is a bit different to manage...  I have a proposal of code refactoring of js to make it work in all cases... To see together.

2025-02-19 09:40 UTC, hannahiss commented
> We should probably map `.btn-link` to `.btn-minimal`

This should be treated in the Link PR

2025-02-19 09:54 UTC, hannahiss commented on site/content/docs/0.0/examples/loading-buttons/loading-buttons.js
> +      statusMessage1.innerHTML = `${statusMessage1.innerHTML}.`
This has been approved by Vincent when we tested it together, because we couldn't find a better way. I think we can go on like this and when it will be finalized, Vincent will approve it officially (or not, and in this case we will change what is asked).

2025-02-19 09:57 UTC, hannahiss commented on site/content/docs/0.0/examples/loading-buttons/loading-buttons.js
> +      loadingButton1.focus()
This has been approved by Vincent when we tested it together, to have the same behavior on different browsers. I think we can go on like this and when it will be finalized, Vincent will approve it officially (or not, and in this case we will change what is asked).

2025-02-19 10:04 UTC, hannahiss commented on site/content/docs/0.0/components/buttons.md
> +## Block buttons
Tried it, it seems to work fine

2025-02-19 10:34 UTC, hannahiss commented on site/content/docs/0.0/examples/loading-buttons/index.html
Added a `<a>` in live examples and some more instructions to disable the link. `<input>` cannot be used in this case (not possible to have an icon in it).

2025-02-19 11:03 UTC, hannahiss commented on site/content/docs/0.0/components/buttons.md
> +- Remove the `.d-none` from the animated `<svg>` and the status message `<span>`.
Changed CSS to make it work automatically but we had to use a small trick to do it (double selector `.btn-icon.btn-icon`)

2025-02-24 14:26 UTC, vprothais requested changes

2025-02-24 14:26 UTC, vprothais commented on site/content/docs/0.1/helpers/stacks.md
> +  <button type="button" class="btn btn-strong">Save changes</button>
Since button is now available, shouldn't we uncomment the "Example" section here to make it available in the documentation ? (we can still keep vertical rule commented)

2025-02-24 14:26 UTC, vprothais commented on site/content/docs/0.1/examples/loading-buttons/index.html
> +  <h2 class="py-short">Loading button in an indeterminate time</h2>
I have a doubt concerning this sentence. It sounds weird but I'm not sure what should be changed :)

Loading button with an indeterminate loading time ?

2025-02-24 14:26 UTC, vprothais commented on site/content/docs/0.1/examples/loading-buttons/index.html
> +  <h2 class="py-short">Loading buttons in a determinate time</h2>
Same feeling here than on the first one :)

2025-02-24 14:26 UTC, vprothais commented on site/content/docs/0.1/customize/options.md
> +| `$enable-gradients`               | `true` or `false` (default)           | Enables predefined gradients via `background-image` styles on various components. |
Shouldn't we add this variable to the migration guide ?

2025-02-24 14:26 UTC, vprothais commented on site/content/docs/0.1/utilities/position.md
> +<div class="position-relative py-short px-tallest text-bg-secondary border border-emphasized">
I'm not sure this kind of thing will be authorized by design, should we keep it in the documentation ?

2025-02-24 14:51 UTC, hannahiss commented on site/content/docs/0.1/helpers/stacks.md
> +  <button type="button" class="btn btn-strong">Save changes</button>
I think you meant horizontal rule commented? 
Anyway this is a good question since we don't have this kind of rules for now? What about OB1?

2025-02-24 14:53 UTC, hannahiss commented on site/content/docs/0.1/examples/loading-buttons/index.html
> +  <h2 class="py-short">Loading button in an indeterminate time</h2>
Can you explain what is weird? We have to types of loading buttons, with a different animation (indeterminate time or determinate time)
Anyway, if you find it weird, our users surely will too...

2025-02-24 15:53 UTC, vprothais commented on site/content/docs/0.1/examples/loading-buttons/index.html
> +  <h2 class="py-short">Loading button in an indeterminate time</h2>
Yeah I understand the idea, I think it is understandable. I was mainly asking myself if the sentence was good in english. I feels like there is a mistake or something but not sure. Not really important, we could ask our English friends later if needed :)

2025-02-25 15:06 UTC, vprothais commented on site/content/docs/0.1/utilities/position.md
> +<button type="button" class="btn btn-strong position-relative">
Both element positioned thanks to the utility are using the `badge` class that is not ready yet on our side. During the daily meeting this morning we though it would be better to comment them for now and show them only when the badge is available.

2025-02-25 15:58 UTC, louismaximepiton commented on site/content/docs/0.1/components/buttons.md
> +Add `.btn-icon` to get a squared button, meant to only contain an icon. Make sure to provide an accessible name to your button, either using a `.visually-hidden` content or an `aria-label` attribute.
I think it'll be taken into account later on when the tooltip will be available, made a comment about this.

2025-02-25 16:05 UTC, louismaximepiton commented on scss/_buttons.scss
> +  // OUDS mod: no fieldset:disabled &,
Maybe we'll see while tackling the forms. What do you think ?

2025-02-25 16:10 UTC, vprothais commented on site/content/docs/0.1/components/buttons.md
> +Add `.btn-icon` to get a squared button, meant to only contain an icon. Make sure to provide an accessible name to your button, either using a `.visually-hidden` content or an `aria-label` attribute.
yeah ok with that, probably better than the title

2025-02-26 11:16 UTC, vprothais approved these changes

2025-02-26 11:20 UTC, merged

2025-02-28 10:09 UTC, Aniort commented
ok 👌 a11y review

2025-03-03 18:04 UTC, Franco-Riccitelli commented
For the design review, the Buttons all look ok.

I just had a question regarding the documentation for the **Variants on colored background** section.
The example shows the buttons on a red background. This combination is not accessible for the **Default** and **Minimal** button variants. Should this example be removed and instead just show the buttons on the orange background?

<img width="135" alt="Screenshot 2025-03-03 at 5 52 36 PM" src="https://github.com/user-attachments/assets/ac17f68b-7372-4ec7-8596-a7e7cc4b1895" />
<img width="135" alt="Screenshot 2025-03-03 at 5 55 57 PM" src="https://github.com/user-attachments/assets/f1785d0d-2184-4efe-85a6-c0e2b81809e5" />