chore(merge main): patched commit → ec96eac
Orange-OpenSource/Orange-Boosted-Bootstrap pull request #2809
Opened 2024-12-02 16:38 UTC by louismaximepiton

- [x] https://github.com/twbs/bootstrap/commit/fa3ad0bfd37e137f1e075dc0173b29daffec7fc1
- [x] https://github.com/twbs/bootstrap/commit/9708bcced8f71ec9b740609ace17fb1617539a05
- [x] https://github.com/twbs/bootstrap/commit/c2a7d686de56f5cdb829c63e1b3849a2c04409d0
- [x] https://github.com/twbs/bootstrap/commit/cbbb567b637e24882fd0fad62bca49e248afb9a4
- [x] https://github.com/twbs/bootstrap/commit/f9b32bc3dedef5ddeb2271c6d03d80e0b0f1471f
- [x] ~~https://github.com/twbs/bootstrap/commit/cacbdc680ecdfee5f0c7fbb876ad15188eaf697d~~ We don't have floating labels.
- [x] https://github.com/twbs/bootstrap/commit/700273886570d0734176087aec0f4d277446b5c5
- [x] https://github.com/twbs/bootstrap/commit/ec96eacd0e6f297a64ee058b22ce9f567c0860e3

2024-12-03 09:50 UTC, julien-deramond commented on package.json
> +    "vnu-jar": "^24.10.17"
Be careful, it's not with a "^" on Bootstrap

```suggestion
    "vnu-jar": "24.10.17"
```

2024-12-05 16:12 UTC, vprothais requested changes

2024-12-05 16:12 UTC, vprothais commented on package.json
> +    "vnu-jar": "23.4.11"
The version doesn't match the one on Bootstrap :
```suggestion
    "vnu-jar": "24.10.17"
```
Defined in [this commit](https://github.com/twbs/bootstrap/commit/c2a7d686de56f5cdb829c63e1b3849a2c04409d0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R157)

2024-12-05 16:25 UTC, vprothais commented on package.json
> +    "vnu-jar": "23.4.11"
Oh I just saw that you got back from this version in a previous commit. I suppose it's linked to the compatibility issue with java version in the runner if it's related to [this error message](https://app.netlify.com/sites/boosted/deploys/674de27324fa040008dc6958#L289)

I'm a netlify newbie but from the documentation it seems we can't do anything about that on our side :/

2024-12-05 16:28 UTC, vprothais approved these changes

2024-12-09 15:27 UTC, vprothais approved these changes

2024-12-10 07:21 UTC, merged